javac ConnectTODB.java
javac User.java
javac searchCompany.java
javac addCompany.java
javac removeCompany.java
javac companyReport.java
javac modifyCompany.java
javac searchSupplier.java
javac SupplierReport.java
javac addSupplier.java
javac removeSupplier.java
javac modifySupplier.java
javac searchProduct.java
javac ProductReport.java
javac addProduct.java
javac deleteProduct.java
javac modProd.java
javac searchCustomer.java
javac CustomerReport.java
javac addCustomer.java
javac removeCustomer.java
javac modifyCustomer.java
javac issueBill.java
javac issueSaleBill.java
javac Report.java
javac dispItemRecord.java
javac About.java
javac master.java
javac Login1.java
java Login1